# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.block_references_info import BlockReferencesInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestBlockReferencesInfo(unittest.TestCase):
    """BlockReferencesInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockReferencesInfo(self):
        """Test BlockReferencesInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.block_references_info.BlockReferencesInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
