# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ergo_explorer_client
from ergo_explorer_client.models.u_output_info import UOutputInfo  # noqa: E501
from ergo_explorer_client.rest import ApiException


class TestUOutputInfo(unittest.TestCase):
    """UOutputInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUOutputInfo(self):
        """Test UOutputInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.u_output_info.UOutputInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
