# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ergo_explorer_client
from ergo_explorer_client.models.network_stats import NetworkStats  # noqa: E501
from ergo_explorer_client.rest import ApiException


class TestNetworkStats(unittest.TestCase):
    """NetworkStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkStats(self):
        """Test NetworkStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.network_stats.NetworkStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
