# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.u_input_info import UInputInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestUInputInfo(unittest.TestCase):
    """UInputInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUInputInfo(self):
        """Test UInputInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.u_input_info.UInputInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
