# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.network_state import NetworkState  # noqa: E501
from swagger_client.rest import ApiException


class TestNetworkState(unittest.TestCase):
    """NetworkState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkState(self):
        """Test NetworkState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.network_state.NetworkState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
