# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ergo_explorer_client
from ergo_explorer_client.models.one_of_list_output_info import OneOfListOutputInfo  # noqa: E501
from ergo_explorer_client.rest import ApiException


class TestOneOfListOutputInfo(unittest.TestCase):
    """OneOfListOutputInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfListOutputInfo(self):
        """Test OneOfListOutputInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_list_output_info.OneOfListOutputInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
