# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ergo_explorer_client
from ergo_explorer_client.models.tuple3_byte_byte_byte import Tuple3ByteByteByte  # noqa: E501
from ergo_explorer_client.rest import ApiException


class TestTuple3ByteByteByte(unittest.TestCase):
    """Tuple3ByteByteByte unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTuple3ByteByteByte(self):
        """Test Tuple3ByteByteByte"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tuple3_byte_byte_byte.Tuple3ByteByteByte()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
