# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Balance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nano_ergs': 'int',
        'tokens': 'list[TokenAmount]'
    }

    attribute_map = {
        'nano_ergs': 'nanoErgs',
        'tokens': 'tokens'
    }

    def __init__(self, nano_ergs=None, tokens=None):  # noqa: E501
        """Balance - a model defined in Swagger"""  # noqa: E501
        self._nano_ergs = None
        self._tokens = None
        self.discriminator = None
        self.nano_ergs = nano_ergs
        if tokens is not None:
            self.tokens = tokens

    @property
    def nano_ergs(self):
        """Gets the nano_ergs of this Balance.  # noqa: E501

        Ergo balance  # noqa: E501

        :return: The nano_ergs of this Balance.  # noqa: E501
        :rtype: int
        """
        return self._nano_ergs

    @nano_ergs.setter
    def nano_ergs(self, nano_ergs):
        """Sets the nano_ergs of this Balance.

        Ergo balance  # noqa: E501

        :param nano_ergs: The nano_ergs of this Balance.  # noqa: E501
        :type: int
        """
        if nano_ergs is None:
            raise ValueError("Invalid value for `nano_ergs`, must not be `None`")  # noqa: E501

        self._nano_ergs = nano_ergs

    @property
    def tokens(self):
        """Gets the tokens of this Balance.  # noqa: E501

        Tokens balances  # noqa: E501

        :return: The tokens of this Balance.  # noqa: E501
        :rtype: list[TokenAmount]
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens):
        """Sets the tokens of this Balance.

        Tokens balances  # noqa: E501

        :param tokens: The tokens of this Balance.  # noqa: E501
        :type: list[TokenAmount]
        """

        self._tokens = tokens

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Balance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Balance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
