# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BlockSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'block': 'FullBlockInfo',
        'references': 'BlockReferencesInfo'
    }

    attribute_map = {
        'block': 'block',
        'references': 'references'
    }

    def __init__(self, block=None, references=None):  # noqa: E501
        """BlockSummary - a model defined in Swagger"""  # noqa: E501
        self._block = None
        self._references = None
        self.discriminator = None
        self.block = block
        self.references = references

    @property
    def block(self):
        """Gets the block of this BlockSummary.  # noqa: E501


        :return: The block of this BlockSummary.  # noqa: E501
        :rtype: FullBlockInfo
        """
        return self._block

    @block.setter
    def block(self, block):
        """Sets the block of this BlockSummary.


        :param block: The block of this BlockSummary.  # noqa: E501
        :type: FullBlockInfo
        """
        if block is None:
            raise ValueError("Invalid value for `block`, must not be `None`")  # noqa: E501

        self._block = block

    @property
    def references(self):
        """Gets the references of this BlockSummary.  # noqa: E501


        :return: The references of this BlockSummary.  # noqa: E501
        :rtype: BlockReferencesInfo
        """
        return self._references

    @references.setter
    def references(self, references):
        """Sets the references of this BlockSummary.


        :param references: The references of this BlockSummary.  # noqa: E501
        :type: BlockReferencesInfo
        """
        if references is None:
            raise ValueError("Invalid value for `references`, must not be `None`")  # noqa: E501

        self._references = references

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BlockSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
