# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BlockReferencesInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'previous_id': 'str',
        'next_id': 'str'
    }

    attribute_map = {
        'previous_id': 'previousId',
        'next_id': 'nextId'
    }

    def __init__(self, previous_id=None, next_id=None):  # noqa: E501
        """BlockReferencesInfo - a model defined in Swagger"""  # noqa: E501
        self._previous_id = None
        self._next_id = None
        self.discriminator = None
        self.previous_id = previous_id
        if next_id is not None:
            self.next_id = next_id

    @property
    def previous_id(self):
        """Gets the previous_id of this BlockReferencesInfo.  # noqa: E501

        ID of the previous block  # noqa: E501

        :return: The previous_id of this BlockReferencesInfo.  # noqa: E501
        :rtype: str
        """
        return self._previous_id

    @previous_id.setter
    def previous_id(self, previous_id):
        """Sets the previous_id of this BlockReferencesInfo.

        ID of the previous block  # noqa: E501

        :param previous_id: The previous_id of this BlockReferencesInfo.  # noqa: E501
        :type: str
        """
        if previous_id is None:
            raise ValueError("Invalid value for `previous_id`, must not be `None`")  # noqa: E501

        self._previous_id = previous_id

    @property
    def next_id(self):
        """Gets the next_id of this BlockReferencesInfo.  # noqa: E501

        ID of the next block (if one exists)  # noqa: E501

        :return: The next_id of this BlockReferencesInfo.  # noqa: E501
        :rtype: str
        """
        return self._next_id

    @next_id.setter
    def next_id(self, next_id):
        """Sets the next_id of this BlockReferencesInfo.

        ID of the next block (if one exists)  # noqa: E501

        :param next_id: The next_id of this BlockReferencesInfo.  # noqa: E501
        :type: str
        """

        self._next_id = next_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BlockReferencesInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockReferencesInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
