# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BoxAssetsQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ergo_tree_template_hash': 'str',
        'assets': 'list[str]'
    }

    attribute_map = {
        'ergo_tree_template_hash': 'ergoTreeTemplateHash',
        'assets': 'assets'
    }

    def __init__(self, ergo_tree_template_hash=None, assets=None):  # noqa: E501
        """BoxAssetsQuery - a model defined in Swagger"""  # noqa: E501
        self._ergo_tree_template_hash = None
        self._assets = None
        self.discriminator = None
        self.ergo_tree_template_hash = ergo_tree_template_hash
        if assets is not None:
            self.assets = assets

    @property
    def ergo_tree_template_hash(self):
        """Gets the ergo_tree_template_hash of this BoxAssetsQuery.  # noqa: E501

        SHA-256 hash of ErgoTree template this box script should have  # noqa: E501

        :return: The ergo_tree_template_hash of this BoxAssetsQuery.  # noqa: E501
        :rtype: str
        """
        return self._ergo_tree_template_hash

    @ergo_tree_template_hash.setter
    def ergo_tree_template_hash(self, ergo_tree_template_hash):
        """Sets the ergo_tree_template_hash of this BoxAssetsQuery.

        SHA-256 hash of ErgoTree template this box script should have  # noqa: E501

        :param ergo_tree_template_hash: The ergo_tree_template_hash of this BoxAssetsQuery.  # noqa: E501
        :type: str
        """
        if ergo_tree_template_hash is None:
            raise ValueError("Invalid value for `ergo_tree_template_hash`, must not be `None`")  # noqa: E501

        self._ergo_tree_template_hash = ergo_tree_template_hash

    @property
    def assets(self):
        """Gets the assets of this BoxAssetsQuery.  # noqa: E501

        IDs of tokens returned boxes should contain  # noqa: E501

        :return: The assets of this BoxAssetsQuery.  # noqa: E501
        :rtype: list[str]
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this BoxAssetsQuery.

        IDs of tokens returned boxes should contain  # noqa: E501

        :param assets: The assets of this BoxAssetsQuery.  # noqa: E501
        :type: list[str]
        """

        self._assets = assets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BoxAssetsQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BoxAssetsQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
