# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataInputInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'box_id': 'str',
        'value': 'int',
        'index': 'int',
        'output_block_id': 'str',
        'output_transaction_id': 'str',
        'output_index': 'int',
        'ergo_tree': 'str',
        'address': 'str',
        'assets': 'list[AssetInstanceInfo]',
        'additional_registers': 'dict(str, str)'
    }

    attribute_map = {
        'box_id': 'boxId',
        'value': 'value',
        'index': 'index',
        'output_block_id': 'outputBlockId',
        'output_transaction_id': 'outputTransactionId',
        'output_index': 'outputIndex',
        'ergo_tree': 'ergoTree',
        'address': 'address',
        'assets': 'assets',
        'additional_registers': 'additionalRegisters'
    }

    def __init__(self, box_id=None, value=None, index=None, output_block_id=None, output_transaction_id=None, output_index=None, ergo_tree=None, address=None, assets=None, additional_registers=None):  # noqa: E501
        """DataInputInfo - a model defined in Swagger"""  # noqa: E501
        self._box_id = None
        self._value = None
        self._index = None
        self._output_block_id = None
        self._output_transaction_id = None
        self._output_index = None
        self._ergo_tree = None
        self._address = None
        self._assets = None
        self._additional_registers = None
        self.discriminator = None
        self.box_id = box_id
        self.value = value
        self.index = index
        self.output_block_id = output_block_id
        self.output_transaction_id = output_transaction_id
        self.output_index = output_index
        self.ergo_tree = ergo_tree
        self.address = address
        if assets is not None:
            self.assets = assets
        self.additional_registers = additional_registers

    @property
    def box_id(self):
        """Gets the box_id of this DataInputInfo.  # noqa: E501

        ID of the corresponding box  # noqa: E501

        :return: The box_id of this DataInputInfo.  # noqa: E501
        :rtype: str
        """
        return self._box_id

    @box_id.setter
    def box_id(self, box_id):
        """Sets the box_id of this DataInputInfo.

        ID of the corresponding box  # noqa: E501

        :param box_id: The box_id of this DataInputInfo.  # noqa: E501
        :type: str
        """
        if box_id is None:
            raise ValueError("Invalid value for `box_id`, must not be `None`")  # noqa: E501

        self._box_id = box_id

    @property
    def value(self):
        """Gets the value of this DataInputInfo.  # noqa: E501

        Number of nanoErgs in the corresponding box  # noqa: E501

        :return: The value of this DataInputInfo.  # noqa: E501
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DataInputInfo.

        Number of nanoErgs in the corresponding box  # noqa: E501

        :param value: The value of this DataInputInfo.  # noqa: E501
        :type: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def index(self):
        """Gets the index of this DataInputInfo.  # noqa: E501

        Index of the input in a transaction  # noqa: E501

        :return: The index of this DataInputInfo.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this DataInputInfo.

        Index of the input in a transaction  # noqa: E501

        :param index: The index of this DataInputInfo.  # noqa: E501
        :type: int
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501

        self._index = index

    @property
    def output_block_id(self):
        """Gets the output_block_id of this DataInputInfo.  # noqa: E501

        Modifier ID  # noqa: E501

        :return: The output_block_id of this DataInputInfo.  # noqa: E501
        :rtype: str
        """
        return self._output_block_id

    @output_block_id.setter
    def output_block_id(self, output_block_id):
        """Sets the output_block_id of this DataInputInfo.

        Modifier ID  # noqa: E501

        :param output_block_id: The output_block_id of this DataInputInfo.  # noqa: E501
        :type: str
        """
        if output_block_id is None:
            raise ValueError("Invalid value for `output_block_id`, must not be `None`")  # noqa: E501

        self._output_block_id = output_block_id

    @property
    def output_transaction_id(self):
        """Gets the output_transaction_id of this DataInputInfo.  # noqa: E501

        ID of the transaction outputting corresponding box  # noqa: E501

        :return: The output_transaction_id of this DataInputInfo.  # noqa: E501
        :rtype: str
        """
        return self._output_transaction_id

    @output_transaction_id.setter
    def output_transaction_id(self, output_transaction_id):
        """Sets the output_transaction_id of this DataInputInfo.

        ID of the transaction outputting corresponding box  # noqa: E501

        :param output_transaction_id: The output_transaction_id of this DataInputInfo.  # noqa: E501
        :type: str
        """
        if output_transaction_id is None:
            raise ValueError("Invalid value for `output_transaction_id`, must not be `None`")  # noqa: E501

        self._output_transaction_id = output_transaction_id

    @property
    def output_index(self):
        """Gets the output_index of this DataInputInfo.  # noqa: E501

        Index of the output corresponding this input  # noqa: E501

        :return: The output_index of this DataInputInfo.  # noqa: E501
        :rtype: int
        """
        return self._output_index

    @output_index.setter
    def output_index(self, output_index):
        """Sets the output_index of this DataInputInfo.

        Index of the output corresponding this input  # noqa: E501

        :param output_index: The output_index of this DataInputInfo.  # noqa: E501
        :type: int
        """
        if output_index is None:
            raise ValueError("Invalid value for `output_index`, must not be `None`")  # noqa: E501

        self._output_index = output_index

    @property
    def ergo_tree(self):
        """Gets the ergo_tree of this DataInputInfo.  # noqa: E501

        Hex-encoded string  # noqa: E501

        :return: The ergo_tree of this DataInputInfo.  # noqa: E501
        :rtype: str
        """
        return self._ergo_tree

    @ergo_tree.setter
    def ergo_tree(self, ergo_tree):
        """Sets the ergo_tree of this DataInputInfo.

        Hex-encoded string  # noqa: E501

        :param ergo_tree: The ergo_tree of this DataInputInfo.  # noqa: E501
        :type: str
        """
        if ergo_tree is None:
            raise ValueError("Invalid value for `ergo_tree`, must not be `None`")  # noqa: E501

        self._ergo_tree = ergo_tree

    @property
    def address(self):
        """Gets the address of this DataInputInfo.  # noqa: E501

        Decoded address of the corresponding box holder  # noqa: E501

        :return: The address of this DataInputInfo.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this DataInputInfo.

        Decoded address of the corresponding box holder  # noqa: E501

        :param address: The address of this DataInputInfo.  # noqa: E501
        :type: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def assets(self):
        """Gets the assets of this DataInputInfo.  # noqa: E501


        :return: The assets of this DataInputInfo.  # noqa: E501
        :rtype: list[AssetInstanceInfo]
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this DataInputInfo.


        :param assets: The assets of this DataInputInfo.  # noqa: E501
        :type: list[AssetInstanceInfo]
        """

        self._assets = assets

    @property
    def additional_registers(self):
        """Gets the additional_registers of this DataInputInfo.  # noqa: E501


        :return: The additional_registers of this DataInputInfo.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._additional_registers

    @additional_registers.setter
    def additional_registers(self, additional_registers):
        """Sets the additional_registers of this DataInputInfo.


        :param additional_registers: The additional_registers of this DataInputInfo.  # noqa: E501
        :type: dict(str, str)
        """
        if additional_registers is None:
            raise ValueError("Invalid value for `additional_registers`, must not be `None`")  # noqa: E501

        self._additional_registers = additional_registers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataInputInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataInputInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
