# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NetworkStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_addresses_num': 'int'
    }

    attribute_map = {
        'unique_addresses_num': 'uniqueAddressesNum'
    }

    def __init__(self, unique_addresses_num=None):  # noqa: E501
        """NetworkStats - a model defined in Swagger"""  # noqa: E501
        self._unique_addresses_num = None
        self.discriminator = None
        self.unique_addresses_num = unique_addresses_num

    @property
    def unique_addresses_num(self):
        """Gets the unique_addresses_num of this NetworkStats.  # noqa: E501


        :return: The unique_addresses_num of this NetworkStats.  # noqa: E501
        :rtype: int
        """
        return self._unique_addresses_num

    @unique_addresses_num.setter
    def unique_addresses_num(self, unique_addresses_num):
        """Sets the unique_addresses_num of this NetworkStats.


        :param unique_addresses_num: The unique_addresses_num of this NetworkStats.  # noqa: E501
        :type: int
        """
        if unique_addresses_num is None:
            raise ValueError("Invalid value for `unique_addresses_num`, must not be `None`")  # noqa: E501

        self._unique_addresses_num = unique_addresses_num

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
