# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TotalBalance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'confirmed': 'Balance',
        'unconfirmed': 'Balance'
    }

    attribute_map = {
        'confirmed': 'confirmed',
        'unconfirmed': 'unconfirmed'
    }

    def __init__(self, confirmed=None, unconfirmed=None):  # noqa: E501
        """TotalBalance - a model defined in Swagger"""  # noqa: E501
        self._confirmed = None
        self._unconfirmed = None
        self.discriminator = None
        self.confirmed = confirmed
        self.unconfirmed = unconfirmed

    @property
    def confirmed(self):
        """Gets the confirmed of this TotalBalance.  # noqa: E501


        :return: The confirmed of this TotalBalance.  # noqa: E501
        :rtype: Balance
        """
        return self._confirmed

    @confirmed.setter
    def confirmed(self, confirmed):
        """Sets the confirmed of this TotalBalance.


        :param confirmed: The confirmed of this TotalBalance.  # noqa: E501
        :type: Balance
        """
        if confirmed is None:
            raise ValueError("Invalid value for `confirmed`, must not be `None`")  # noqa: E501

        self._confirmed = confirmed

    @property
    def unconfirmed(self):
        """Gets the unconfirmed of this TotalBalance.  # noqa: E501


        :return: The unconfirmed of this TotalBalance.  # noqa: E501
        :rtype: Balance
        """
        return self._unconfirmed

    @unconfirmed.setter
    def unconfirmed(self, unconfirmed):
        """Sets the unconfirmed of this TotalBalance.


        :param unconfirmed: The unconfirmed of this TotalBalance.  # noqa: E501
        :type: Balance
        """
        if unconfirmed is None:
            raise ValueError("Invalid value for `unconfirmed`, must not be `None`")  # noqa: E501

        self._unconfirmed = unconfirmed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TotalBalance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TotalBalance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
