# coding: utf-8

"""
    Ergo Explorer API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Tuple3ByteByteByte(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_1': 'int',
        '_2': 'int',
        '_3': 'int'
    }

    attribute_map = {
        '_1': '_1',
        '_2': '_2',
        '_3': '_3'
    }

    def __init__(self, _1=None, _2=None, _3=None):  # noqa: E501
        """Tuple3ByteByteByte - a model defined in Swagger"""  # noqa: E501
        self.__1 = None
        self.__2 = None
        self.__3 = None
        self.discriminator = None
        self._1 = _1
        self._2 = _2
        self._3 = _3

    @property
    def _1(self):
        """Gets the _1 of this Tuple3ByteByteByte.  # noqa: E501


        :return: The _1 of this Tuple3ByteByteByte.  # noqa: E501
        :rtype: int
        """
        return self.__1

    @_1.setter
    def _1(self, _1):
        """Sets the _1 of this Tuple3ByteByteByte.


        :param _1: The _1 of this Tuple3ByteByteByte.  # noqa: E501
        :type: int
        """
        if _1 is None:
            raise ValueError("Invalid value for `_1`, must not be `None`")  # noqa: E501

        self.__1 = _1

    @property
    def _2(self):
        """Gets the _2 of this Tuple3ByteByteByte.  # noqa: E501


        :return: The _2 of this Tuple3ByteByteByte.  # noqa: E501
        :rtype: int
        """
        return self.__2

    @_2.setter
    def _2(self, _2):
        """Sets the _2 of this Tuple3ByteByteByte.


        :param _2: The _2 of this Tuple3ByteByteByte.  # noqa: E501
        :type: int
        """
        if _2 is None:
            raise ValueError("Invalid value for `_2`, must not be `None`")  # noqa: E501

        self.__2 = _2

    @property
    def _3(self):
        """Gets the _3 of this Tuple3ByteByteByte.  # noqa: E501


        :return: The _3 of this Tuple3ByteByteByte.  # noqa: E501
        :rtype: int
        """
        return self.__3

    @_3.setter
    def _3(self, _3):
        """Sets the _3 of this Tuple3ByteByteByte.


        :param _3: The _3 of this Tuple3ByteByteByte.  # noqa: E501
        :type: int
        """
        if _3 is None:
            raise ValueError("Invalid value for `_3`, must not be `None`")  # noqa: E501

        self.__3 = _3

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Tuple3ByteByteByte, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tuple3ByteByteByte):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
